# Exercícios - fatiamento

In [4]:
import numpy as np

In [15]:
# 2. Crie um array data com as seguite lista [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
# 3. Selecione apenas os dados diferentes de 4,6,8,10
data_2 = data[(data !=4) & (data != 6) & (data!= 8) & (data != 10)]

In [14]:
data_2

array([ 1,  2,  3,  5,  7,  9, 11, 12, 13, 14, 15, 16])

In [16]:
# 4. Crie um array dim2 que tenha 2 dimensões e a lista [1,2,3,4,5] na primeira linha e a lista [6,7,8,9,10] na segunda linha
dim2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [18]:
dim2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
# 5. Crie um array chamado dim2_2 que seja uma fatia de dim2 e que contenha apenas os valores 3,4,8,9
dim2_2 = dim2[:,2:4]

In [21]:
dim2_2

array([[3, 4],
       [8, 9]])

# Prática

In [23]:
import numpy as np

In [25]:
np.array([9, 8, 7]) #Uma dimensão

array([9, 8, 7])

In [28]:
np.array( [ [ 11, 2, 33 ], [ 100, 2, 4000 ] ] ) #Bidimensional

array([[  11,    2,   33],
       [ 100,    2, 4000]])

In [41]:
np.array( [ [ [ 22, 56, 38 ], [ 114, 489, 878 ], [ 1001, 1002, 11000] ] ] ) #Tridimensional

<function numpy.array>

In [43]:
one = np.ones([2, 2])

In [44]:
array9 = np.diag((2, 1, 4, 6)) ; array9 #matriz diagonal

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [56]:
np.random.seed(100)
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [64]:
array11 = np.random.randn(5) ;array11

array([ 1.15117366, -1.02933685, -0.51099219, -2.36027053,  0.10359513])

In [65]:
zeros = np.zeros([2, 2, 2])
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [77]:
array19 = np.arange(0, 30) * 5
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [81]:
data = np.arange(21) ; data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [82]:
# Fatiamento

In [83]:
data[10:16]

array([10, 11, 12, 13, 14, 15])

In [85]:
data[10:16] = -101 ; data

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, -101,
       -101, -101, -101, -101, -101,   16,   17,   18,   19,   20])

In [87]:
dat1 = data[10:17]
dat1 [2:4] = 2021 ; dat1

array([-101, -101, 2021, 2021, -101, -101,   16])

In [89]:
data_2 = data[7:].copy() ;data_2

array([   7,    8,    9, -101, -101, 2021, 2021, -101, -101,   16,   17,
         18,   19,   20])

In [91]:
dados = np.arange(100) ; dados

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [92]:
dados[dados > 93]

array([94, 95, 96, 97, 98, 99])

In [94]:
dados [dados != 20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [102]:
dados_2 = dados[ ( dados != 10 ) & ( dados != 20 ) & ( dados != 30 ) ] ; dados_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [107]:
dados_2.shape

(97,)